---
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
exclude: >
  (?x)^(
    .yarn/.*|
    pnpm-lock.yaml|
    .config/dictionary.txt|
    packages/vscode-ansible/syntaxes/external/.*|
    packages/ansible-language-server/test/fixtures/diagnostics/invalid_yaml.yml|
    packages/vscode-ansible/syntaxes/external/jinja.tmLanguage.json|
    packages/ansible-language-server/.vscode/extensions.json|
    packages/vscode-ansible/test/testFixtures/diagnostics/yaml/invalid_yaml.yml
  )$
minimum_pre_commit_version: 2.9.0 # types_or
repos:
  - repo: local
    hooks:
      - id: git-dirty
        name: Check if git reports dirty
        entry: git diff --exit-code
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        args:
          - --color=always

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: >
          (?x)^(
            .yarn/.*|
            examples/playbooks/(with-skip-tag-id|unicode).yml|
            examples/playbooks/example.yml
          )$
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.17.0
    hooks:
      - id: cspell
        name: Spell check with cspell
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before markdownlint and eslint
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        types_or: ["markdown", "json", "ts"]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.30.0
    hooks:
      - id: eslint
        args:
          - --fix
          - --max-warnings
          - "0"
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - eslint
          - eslint-plugin-prettier
          - eslint-config-prettier
          - prettier
          - typescript
          - typescript-eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
