# This is a basic workflow

name: ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: ["main", "devel/*"]
  pull_request:
    branches: ["main", "devel/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"  # make mocha output colorful

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: ${{ matrix.name }}
    # ${{ matrix.name && matrix.name || format('{0} ({1})', matrix.task-name, matrix.os) }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: lint
            task-name: lint
            os: ubuntu-22.04
            upload-artifact: true
            env:
              SKIP_PODMAN: 1
              SKIP_DOCKER: 1

          - name: test-ui
            os: ubuntu-22.04
            task-name: test-ui
            upload-artifact: false

          - name: test-ui-old
            os: ubuntu-22.04
            task-name: test-ui-old
            upload-artifact: false

          - name: test-e2e
            os: ubuntu-22.04
            task-name: test-e2e
            upload-artifact: false

          - name: test-ui (macos)
            task-name: test-ui
            os:  macos-12
            env:
              SKIP_PODMAN: 1
              SKIP_DOCKER: 1

          - name: test-ui-old (macos)
            task-name: test-ui-old
            os:  macos-12
            env:
              SKIP_PODMAN: 1
              SKIP_DOCKER: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout vscode-ansible
        uses: actions/checkout@v3.2.0

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Enable caching
        uses: actions/cache@v3
        with:
          path: |
            .vscode-test
            .yarn/cache
            out/ext
            out/test-resources
            out/test-resources-oldest
            ~/.cache/pip
            ~/.cache/yarn
            ~/.local/share/containers/podman/machine/qemu
          key: ${{ runner.os }}-${{ matrix.task-name }}-${{ hashFiles('package.json', 'yarn.lock', '.config/Containerfile') }}

      - name: Use NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: task setup
        run: task setup

      ## uncomment to debug on GHA runner
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: task package
        run: task package --output=group --output-group-begin='::group::{{.TASK}}' --output-group-end='::endgroup::'

      - name: task ${{ matrix.task-name }}
        # xvfb needed for chrome headless tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: task ${{ matrix.task-name }} --output=group --output-group-begin='::group::{{.TASK}}' --output-group-end='::endgroup::'
        continue-on-error: ${{ matrix.continue-on-error || false }}

      - name: Upload vsix artifact
        if: ${{ github.event.number && matrix.upload-artifact }}
        uses: actions/upload-artifact@v3
        with:
          name: ansible-extension-from-pr-${{ github.event.number }}.vsix
          path: ansible-*.vsix
          retention-days: 15

      - name: Upload test logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: logs-${{ matrix.os }}-${{ matrix.task-name }}.zip
          path: |
            out/e2eTestReport
            out/log
            out/test-resources/settings/logs
            out/userdata/logs
          if-no-files-found: ignore
          retention-days: 15

      - name: Stop services
        if: "contains(matrix.os, 'macos')"
        # Stopping podman machine is needed or caching it will fail
        run: |
          command -v podman && {
          podman machine stop
          while [[ "$(podman machine ls --format '{{.Running}}' \
                --noheading || true)" != "false" ]]; do
            sleep 1
            echo -n .
          done
          echo .
          }
        continue-on-error: true

      ## commented out for future use to debug on the GHA node if required
      # - name: Setup tmate session
      #   if: ${{ always() }}
      #   uses: mxschmitt/action-tmate@v3

  check: # This job does nothing and is only used for the branch protection
    if: always()

    needs:
      - build

    runs-on: ubuntu-22.04

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
